
```{r}
#| label: setup

library(tidyverse)
```


```{r}
#| label: factorial_data


multi_fact_data <- read.csv("../Models/factorial_results_v2/multiclass/analysis/factorial_long.csv")
glimpse(multi_fact_data)


binary_fact_data <- read.csv("../Models/factorial_results_v2/binary/analysis/factorial_long.csv")
glimpse(binary_fact_data)


```

```{r}
#| label: data organizing

config_order <- c("fld_nolidar_leafon", "fld_nolidar_leafoff",  "fld_chmret_leafon", "fld_chmret_leafoff", 
                 "nwi_chmret_leafoff", "nwiextra_chmret_leafoff", "nwifield_chmret_leafoff", "flddeg_chmret_leafoff")
multi_fact_data$config <- factor(multi_fact_data$config, levels = config_order)

config_label <- c("fld_nolidar_leafon" = "Field Data\n No Lidar\n No Leaf-Off", "fld_nolidar_leafoff" = "Field Data\n No Lidar\n With Leaf-Off",  
                  "fld_chmret_leafon" = "Field Data\n With Lidar\n No Leaf-Off", "fld_chmret_leafoff" = "Field Data\n With Lidar\n With Leaf-Off", 
                 "nwi_chmret_leafoff" = "NWI Data\n With Lidar\n With Leaf-Off", "nwiextra_chmret_leafoff" = "NWI x2 Data\n With Lidar\n With Leaf-Off", 
                 "nwifield_chmret_leafoff" = "NWI + Field Data\n With Lidar\n With Leaf-Off", "flddeg_chmret_leafoff" = "Field-Degraded Data\n With Lidar\n With Leaf-Off")

class_color <- c("FSW" = "#81b14f", "SSW" = "#c4bd8b", "EMW" = "#8faab3", "UPL" = "#6a4836")

theme_param <- theme(
  text = element_text(size = 10),
  legend.position = 'right',
  legend.key.size = unit(0.6, "cm"),
  legend.spacing.x = unit(1.2, "cm"),
  legend.text = element_text(size = rel(0.70), hjust = 0.5),
  panel.background = element_blank(),
  panel.grid.major = element_line(colour = "grey50", linewidth = 0.2),
  axis.ticks = element_blank(),
  axis.text = element_text(size = rel(0.9)),
  axis.title = element_text(size = rel(1))
)
```


### Does leaf off imagery or lidar-derived metrics improve field-based models? 


```{r}
#| output-location: slide
multi_fact_data |> group_by(spectral) |>
    filter(label == "fld") |> 
    ggplot(aes(x = config, y = f1, fill = class)) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75), size = 5, shape = 21) + 
        scale_fill_manual(values = class_color) + 
        scale_x_discrete(labels = config_label) + 
        theme_param

multi_fact_data |> group_by(spectral) |>
    filter(label == "fld") |> 
    ggplot(aes(x = config, y = iou, fill = class)) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75), size = 5, shape = 21) + 
        scale_fill_manual(values = class_color) + 
        scale_x_discrete(labels = config_label) + 
        theme_param
```


### How do NWI data labels compare to field and GIS-derived data? 

#### Also does degrading the field data hinder its performance?


```{r}
multi_fact_data |> group_by(spectral) |>
    filter(featureset == "chmret_leafoff") |> 
    ggplot(aes(x = config, y = f1, fill = class)) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75), size = 5, shape = 21) + 
        scale_fill_manual(values = class_color) + 
        scale_x_discrete(labels = config_label) + 
        theme_param

multi_fact_data |> group_by(spectral) |>
    filter(featureset == "chmret_leafoff") |> 
    ggplot(aes(x = config, y = iou, fill = class)) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75), size = 5, shape = 21) + 
        scale_fill_manual(values = class_color) + 
        scale_x_discrete(labels = config_label) + 
        theme_param
```



```{r}
multi_fact_data$featureset |> unique()
```